# Generated by Django 4.1.5 on 2023-01-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=100, null=True)),
                ("number", models.CharField(max_length=50)),
                ("complement", models.CharField(max_length=120, null=True)),
                ("zipcode", models.CharField(max_length=50)),
                ("city_state", models.CharField(max_length=50, null=True)),
                ("neighborhood", models.CharField(max_length=50, null=True)),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
