# Generated by Django 4.1.5 on 2023-01-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiary_entity", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="beneficiary_entity",
            old_name="data_do_cadastro",
            new_name="date_created",
        ),
        migrations.RenameField(
            model_name="beneficiary_entity",
            old_name="update_do_cadastro",
            new_name="date_updated",
        ),
    ]
