# Generated by Django 4.1.5 on 2023-01-09 13:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns_projects", "0002_initial"),
        (
            "beneficiary_entity",
            "0003_rename_data_do_cadastro_beneficiary_entity_date_created_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BeneficiaryEntity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("date_created", models.DateField()),
                ("date_updated", models.DateField()),
                ("email", models.EmailField(max_length=60)),
                ("cnpj", models.CharField(max_length=14, unique=True)),
                (
                    "campaigns_projects",
                    models.ManyToManyField(
                        related_name="beneficiary_entity",
                        to="campaigns_projects.campaignsprojects",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Beneficiary_entity",
        ),
    ]
