# Generated by Django 4.1.5 on 2023-01-06 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("campaigns_projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignsprojects",
            name="age_majority",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignsprojects",
            name="voluntary_campaigns",
            field=models.ManyToManyField(
                related_name="campaigns_projects", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
