# Generated by Django 4.1.5 on 2023-01-09 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns_projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignsprojects",
            name="voluntary_campaigns",
            field=models.ManyToManyField(
                related_name="campaigns_projects", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
